### PR TITLE
Feature/model migration

### PR DESCRIPTION
**Pull request by broguinn**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-83700360%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-83714628%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-83738728%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-83750268%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-85172264%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-85174045%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-87702612%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-87720332%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-89333363%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/65%23issuecomment-83700360%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ca%20href%3D%5C%22http%3A//app.review.ninja/agco/harvesterjs/pull/65%5C%22%20target%3D%5C%22_blank%5C%22%3E%3Cimg%20src%3D%5C%22http%3A//app.review.ninja/23838217/pull/65/badge%5C%22%20alt%3D%5C%22ReviewNinja%5C%22/%3E%22%2C%20%22created_at%22%3A%20%222015-03-19T18%3A22%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8714728%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/review-ninja%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/2152172/badge%29%5D%28https%3A//coveralls.io/builds/2152172%29%5Cn%5CnCoverage%20decreased%20%28-11.01%25%29%20to%2071.03%25%20when%20pulling%20%2A%2A9137517bb264c214c3b72ac3fec71592a1343c19%20on%20feature/model_migration%2A%2A%20into%20%2A%2A65df0f53870c5eb9eba515d49ed5a831187d3dcb%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-19T18%3A46%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/2152673/badge%29%5D%28https%3A//coveralls.io/builds/2152673%29%5Cn%5CnCoverage%20decreased%20%28-11.04%25%29%20to%2071.0%25%20when%20pulling%20%2A%2A093fa08efde7f671e564b7127be1f2f185770b73%20on%20feature/model_migration%2A%2A%20into%20%2A%2A65df0f53870c5eb9eba515d49ed5a831187d3dcb%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-19T19%3A55%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/2152873/badge%29%5D%28https%3A//coveralls.io/builds/2152873%29%5Cn%5CnCoverage%20decreased%20%28-11.17%25%29%20to%2070.87%25%20when%20pulling%20%2A%2A259622469ec2a2dab7cea0c5095d9ae0397a3e25%20on%20feature/model_migration%2A%2A%20into%20%2A%2A65df0f53870c5eb9eba515d49ed5a831187d3dcb%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-19T20%3A21%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20good%20at%20first%20glance%5Cn%5Cnwill%20assign%20this%20on%20to%20Stephen%20for%20a%20more%20in-depth%20review%20as%20I%27m%20constrained%20with%20time%20right%20now%22%2C%20%22created_at%22%3A%20%222015-03-23T20%3A09%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/666156%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kristofsajdak%22%7D%7D%2C%20%7B%22body%22%3A%20%22was%20expecting%20that%20we%20would%20remove%20everything%20from%20adapter%20besides%20.schema%20and%20.model%5CnIn%20case%20this%20is%20done%20for%20the%20purpose%20of%20backwards%20compatibility%20I%20suggest%20we%20mark%20the%20other%20functions%20as%20deprecated%20and%20remove%20them%20it%20in%20the%20next%20or%20next%2B1%20release%22%2C%20%22created_at%22%3A%20%222015-03-23T20%3A14%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/666156%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kristofsajdak%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/2223436/badge%29%5D%28https%3A//coveralls.io/builds/2223436%29%5Cn%5CnCoverage%20decreased%20%28-3.16%25%29%20to%2078.91%25%20when%20pulling%20%2A%2A3ae066dac91d79672053dc9829907e6a69211463%20on%20feature/model_migration%2A%2A%20into%20%2A%2Acd359380aafd2ff278987f983d5917906bf75b91%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-30T14%3A31%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/2223739/badge%29%5D%28https%3A//coveralls.io/builds/2223739%29%5Cn%5CnCoverage%20decreased%20%28-2.99%25%29%20to%2079.09%25%20when%20pulling%20%2A%2Ae5e1562313328b2d856dae4a145793f01c535c0a%20on%20feature/model_migration%2A%2A%20into%20%2A%2Acd359380aafd2ff278987f983d5917906bf75b91%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-30T15%3A18%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22Guys%2C%20even%20though%20some%20coverage%20catch-up%20has%20been%20made%20this%20PR%20would%20case%20a%203%25%20drop%2C%20taking%20is%20even%20farther%20from%20the%20%3E85%25%20goal.%20My%20suggestion%20is%20that%20we%20refrain%20from%20merging%20until%20coverage%20is%20either%20equal%20or%20bigger%20than%20the%20target...%22%2C%20%22created_at%22%3A%20%222015-04-03T15%3A46%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/543526%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dclucas%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/agco/harvesterjs/pull/65#issuecomment-83700360'>General Comment</a></b>
- <a href='https://github.com/review-ninja'></a> <a href="http://app.review.ninja/agco/harvesterjs/pull/65" target="_blank">ReviewNinja
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/2152172)
Coverage decreased (-11.01%) to 71.03% when pulling **9137517bb264c214c3b72ac3fec71592a1343c19 on feature/model_migration** into **65df0f53870c5eb9eba515d49ed5a831187d3dcb on develop**.
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/2152673)
Coverage decreased (-11.04%) to 71.0% when pulling **093fa08efde7f671e564b7127be1f2f185770b73 on feature/model_migration** into **65df0f53870c5eb9eba515d49ed5a831187d3dcb on develop**.
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/2152873)
Coverage decreased (-11.17%) to 70.87% when pulling **259622469ec2a2dab7cea0c5095d9ae0397a3e25 on feature/model_migration** into **65df0f53870c5eb9eba515d49ed5a831187d3dcb on develop**.
- <a href='https://github.com/kristofsajdak'></a> Looks good at first glance
will assign this on to Stephen for a more in-depth review as I'm constrained with time right now
- <a href='https://github.com/kristofsajdak'></a> was expecting that we would remove everything from adapter besides .schema and .model
In case this is done for the purpose of backwards compatibility I suggest we mark the other functions as deprecated and remove them it in the next or next+1 release
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/2223436)
Coverage decreased (-3.16%) to 78.91% when pulling **3ae066dac91d79672053dc9829907e6a69211463 on feature/model_migration** into **cd359380aafd2ff278987f983d5917906bf75b91 on develop**.
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/2223739)
Coverage decreased (-2.99%) to 79.09% when pulling **e5e1562313328b2d856dae4a145793f01c535c0a on feature/model_migration** into **cd359380aafd2ff278987f983d5917906bf75b91 on develop**.
- <a href='https://github.com/dclucas'></a> Guys, even though some coverage catch-up has been made this PR would case a 3% drop, taking is even farther from the >85% goal. My suggestion is that we refrain from merging until coverage is either equal or bigger than the target...

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/65?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/65?approve=1'></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/65'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/agco/harvesterjs/pull/65" target="_blank">ReviewNinja

**Comment by kristofsajdak** [comment]
Looks good at first glance

will assign this on to Stephen for a more in-depth review as I'm constrained with time right now

**Comment by kristofsajdak** [comment]
was expecting that we would remove everything from adapter besides .schema and .model
In case this is done for the purpose of backwards compatibility I suggest we mark the other functions as deprecated and remove them it in the next or next+1 release

**Comment by dclucas** [comment]
Guys, even though some coverage catch-up has been made this PR would case a 3% drop, taking is even farther from the >85% goal. My suggestion is that we refrain from merging until coverage is either equal or bigger than the target...

**Comment by ssebro** [comment]
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs

**Pull request closed without merging**
