### PR TITLE
new ready to run Harvesterjs example with docs

### PR DESCRIPTION
**Pull request by kristofsajdak**
added a new working example with a README and a dockerized Mongodb backend. The example registers a change event listener and inserts a new entry in a simple collection

 removed some of the legacy examples, they should be revised (inverse) and updated with relevant use cases

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/agco/harvesterjs/pull/83" target="_blank">ReviewNinja

**Comment by dclucas** [comment]
New code looks good. A couple of suggestions, though:
1. Turn this example into an automated unit test, so that we keep them always working
2. Provide the simplest possible example (no event listener) with as little setup as possible

**Comment by kristofsajdak** [comment]
hmm, not sure about that if I'm honest :-)

I think examples and automated tests both have their merit

Tests assure you don't break things and even communicate really well which features are available, however they tend to have a bit more code surrounding it to set up fixtures etc.

The example gets you up and running fast and allows to start fiddling with the code without too much distraction

I can add an additional example without a listener, but believe this particular example also has it's place as it gets you started with one of the more complex/setup heavy features. It's kind of hard to put all of that together from the automated tests. 

In retrospect I do believe this duplicates some of the work we started in the recipes, let me have a look how we can converge that.

**Comment by dclucas** [comment]
There's a number of things we can do to make the examples runnable. At the
very least, an ugly copy-and-paste of resource setup should prevent some
example breakage.

In the generator, I intend to run npm test against the scaffolded code
(running npm run now, as the code has no tests). A similar approach could
be used here.

I don't see that as a showstopper for this PR, but I will add an issue for
it (which can be dismissed, of course, if no one else sees the value :))

Em Qua, 20 de mai de 2015 16:57, kristofsajdak <notifications@github.com>
escreveu:

**Pull request merged**
